"use client"
import Accordion from "@/components/accordion/page";
import Button from "@/components/ui/button/Button";
import { usePaymentContext } from "@/context/PaymentContext";
import { useTopupContext } from "@/context/TopupContext";
import Image from "next/image";
import { useRouter, useSearchParams } from "next/navigation";
import { TbClockExclamation } from "react-icons/tb";
import { toast } from "sonner";
import { format } from "date-fns";
import { id } from "date-fns/locale";
import { useDetailCustomer } from "@/hooks/useAuth";
import { useEffect, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { usePurchaseContext } from "@/context/PurchaseContext";
import { usePaymentByVA } from "@/hooks/usePayment";
import { IoMdCheckmarkCircle, IoMdCloseCircleOutline } from "react-icons/io";
import { jsPDF } from "jspdf";
import Loading from "@/components/Loading/Loading";


export default function PaymentProcess() {
  const { paymentData, admin_fee } = usePaymentContext();
  const { topupData } = useTopupContext();
  const { purchaseData } = usePurchaseContext();
  const {data} = useDetailCustomer();
  const [isLoading, setIsLoading] = useState(false);

  const searchParams = useSearchParams();
  const idTransaction = searchParams.get('idTransaction') || '';
  const router = useRouter();
  const queryClient = useQueryClient();
  const [mounted, setMounted] = useState(false);

  const paymentHistory = usePaymentByVA(idTransaction);
  console.log(idTransaction);
  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    toast.success(`${label} berhasil disalin!`);
  };

  const getBankLogo = (gateway: string) => {
    switch (gateway.toUpperCase()) {
      case "BAYARIND":
        return "/images/company/bank/bca_logo.png";
      case "NOBU":
        return "/images/company/bank/nobu_logo.png";
      // Tambahkan yang lain jika perlu
      default:
        return "/images/company/bank/logo.png";
    }
  };

  const getBankLogoHistory = (moduleName: string) => {
    switch (moduleName.toUpperCase()) {
      case "BAYARIND_BCA_VIRTUAL_ACCOUNT":
        return "/images/company/bank/bca_logo.png";
      case "BANK_NATIONAL_NOBU_VIRTUAL_ACCOUNT":
        return "/images/company/bank/nobu_logo.png";
      // Tambahkan yang lain jika perlu
      default:
        return "/images/company/bank/logo.png";
    }
  };

  const handleBackHome = () => {
    queryClient.invalidateQueries({ queryKey: ["userById"] });
    router.push("/home");
  }

  useEffect(()=>{
    queryClient.invalidateQueries({ queryKey: ["userById"] });
    setMounted(true);
  },[queryClient]);

  // Function to parse nominal number
  const parseNominal = (text: string) => {
    return text.replace(/[^\d]/g, "");
  };


  const handlePrintPdf = () => {
    setIsLoading(true); // ⏳ Mulai loading

    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const payment = paymentHistory?.data;
    const logoWatermark = '/images/company/logo.png';
    const today = new Date();

    const loadImage = (src: string) =>
      new Promise<HTMLImageElement>((resolve) => {
        const img = new window.Image();
        img.crossOrigin = "anonymous"; 
        img.src = src;
        img.onload = () => resolve(img);
      });

    loadImage(logoWatermark).then((img) => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;

      const ctx = canvas.getContext('2d');
      if (ctx) {
        ctx.globalAlpha = 0.1;
        ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

        const imgData = canvas.toDataURL('image/png');

        doc.setFont("Helvetica", "bold");
        doc.setFontSize(22);
        doc.setTextColor(30, 30, 30);
        doc.text("Payment Receipt", 105, 30, { align: "center" });

        doc.setDrawColor(200, 200, 200);
        doc.line(20, 40, 190, 40);

        doc.setFontSize(13);
        doc.setFont("Helvetica", "normal");
        const details = [
          { label: "Invoice ID", value: payment?.data.invoice_number ?? '-' },
          { label: "Status", value: payment?.data.status_transaction ?? '-' },
          { label: "Amount Paid", value: `Rp ${payment?.data.paid_amount?.toLocaleString('id-ID')}` || 'Rp 0' },
          { label: "Date", value: today.toLocaleString('id-ID', { dateStyle: "full", timeStyle: "short" }) },
          { label: "Virtual Account", value: payment?.data.virtual_account_number ?? '-' },
        ];

        let y = 50;
        details.forEach((item) => {
          doc.text(`${item.label}:`, 25, y);
          doc.text(item.value, 80, y);
          y += 10;
        });

        doc.addImage(imgData, 'PNG', 30, 70, 150, 150, '', 'FAST');

        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by SKY Parking", 105, 140, { align: "center" });

        // ⏳ Save PDF baru setelah semua selesai
        doc.save(`payment-receipt-${payment?.data.invoice_number ?? "unknown"}.pdf`);

        // ✅ SELESAI, matikan loading
        setIsLoading(false);
      }
    }).catch((error) => {
      console.error('Error load image / create PDF:', error);
      setIsLoading(false); // Tetap matikan loading walau error
    });
  };

  if (!mounted) {
    // selama SSR dan sebelum mount, tolak render interaktif
    return null;
  }

  const handleCekStatus = () => {
    router.push("/payment?idTransaction=" + paymentData?.trxId);
  }


  return (
    <div className="min-h-screen bg-white w-full">
      {isLoading && (
        <Loading/>
      )}
      {/* Header Section */}
      <div className="text-center bg-yellow-400 h-72 p-4 rounded-bl-4xl rounded-br-[100px]">
        <div className="w-20 h-20 mx-auto rounded-full bg-white flex items-center justify-center font-bold mb-4">
          {idTransaction !== '' ? (
            paymentHistory.data?.data.status_transaction === "COMPLETED" ? (
              <IoMdCheckmarkCircle size={60} className="text-green-500" />
            ) : paymentHistory.data?.data.status_transaction === "FAILED" ? (
              <IoMdCloseCircleOutline size={60} className="text-red-500" />
            ) : (
              <TbClockExclamation size={60} className="text-yellow-500" />
            )
          ) : (
            <TbClockExclamation size={60} className="text-yellow-500" />
          )}
        </div>
        <h2 className="text-lg font-medium text-orange-800">
          {idTransaction !== '' ? (
            paymentHistory.data?.data.status_transaction === "COMPLETED" ? (
              "Transaksi sudah di bayarkan"
            ) : paymentHistory.data?.data.status_transaction === "FAILED" ? (
              "Transaksi di batalkan oleh sistem"
            ) : (
              "Pesanan berhasil dibuat"
            )
          ) : (
            "Pesanan berhasil dibuat"
          )}
        </h2>
        {idTransaction !== '' ? (
            <p className="text-3xl font-bold text-orange-900">Rp. {Number(paymentHistory.data?.data.paid_amount ).toLocaleString("id-ID") || 0}</p>
          ) : (
            <p className="text-3xl font-bold text-orange-900">Rp. {Number(paymentData!.price ).toLocaleString("id-ID") || 0}</p>
          )
        }
        
        <div className={`${paymentHistory.data?.data.status_transaction === "FAILED" ? '' : 'bg-orange-200'} text-orange-900 p-3 rounded-lg mt-2`}>
          {idTransaction !== '' ? (
            paymentHistory.data?.data.status_transaction === "COMPLETED" ? (
              "Transaksi sudah di bayarkan"
            ) : paymentHistory.data?.data.status_transaction === "FAILED" ? (
              ""
            ) : (
              <>
                <p className="text-sm">Silahkan lakukan pembayaran sebelum</p>
                <p className="text-base font-semibold">{paymentHistory?.data?.data?.expired_date &&
                format(new Date(paymentHistory?.data?.data?.expired_date), "dd MMMM yyyy, HH:mm", {
                  locale: id,
                })}</p>
              </>
            )
          ) : (
            <>
              <p className="text-sm">Selesaikan pembayaran sebelum</p>
              <p className="text-base font-semibold">{paymentData?.expired_date &&
              format(new Date(paymentData.expired_date), "dd MMMM yyyy, HH:mm", {
                locale: id,
              })}</p>
            </>
          )}
          
        </div>
      </div>

      {/* Info Section */}
        <div className="p-4">
          <div className="bg-white rounded-lg p-4 mt-4 shadow-md">
          <div className="flex justify-between items-center w-full">
          <div className="text-sm text-gray-500 font-semibold mb-2">Account an.</div>
          <div className="text-sm text-gray-900 mb-2">{data?.data.username}</div>
        </div>

        <div className="flex justify-between items-center w-full mt-5 mb-2">
            <div className="text-sm text-gray-500 font-semibold">Virtual Account</div>
            {idTransaction !== '' ? (
                <Image src={getBankLogoHistory(paymentHistory?.data?.data.module_name ?? "-")} width={50} height={50} alt="bank logo" />
              ) : (
                <Image src={getBankLogo(topupData?.provider?.gateway_partner ?? purchaseData?.provider?.gateway_partner ?? "-")} width={50} height={50} alt="bank logo" />
              )
            }
            
        </div>
        <div className="flex justify-between items-center mb-4">
          {idTransaction !== '' ? (
                <>
                  <span className="text-sm font-mono">{paymentHistory.data?.data.virtual_account_number}</span>
                  {paymentHistory.data?.data.status_transaction === "FAILED" ? (
                    ""
                  ):(
                    <button
                      className="text-blue-500 text-sm"
                      onClick={() => copyToClipboard(paymentHistory.data?.data.virtual_account_number ?? "-", "Virtual Account")}
                    >
                      📋
                    </button>
                  )}
                  
                </>
              ) : (
                <>
                  <span className="text-sm font-mono">{paymentData?.virtual_account}</span>
                  <button
                    className="text-blue-500 text-sm"
                    onClick={() => copyToClipboard(paymentData?.virtual_account ?? "-", "Virtual Account")}
                  >
                    📋
                  </button>
                </>
              )
          }
        </div>

        <div className="text-sm text-gray-500 font-semibold mb-1">Total Tagihan</div>
        <div className="flex justify-between items-center text-base font-bold text-gray-900 mb-4">
          {idTransaction !== '' ? (
                <>
                  <span className="text-sm font-mono">Rp. {Number(paymentHistory.data?.data.paid_amount || 0 ).toLocaleString("id-ID") || 0}</span>
                  {paymentHistory.data?.data.status_transaction === "FAILED" ? (
                    ""
                  ):(
                    <button
                    className="text-blue-500 text-sm"
                    onClick={() => copyToClipboard(Number(topupData!.nominal.toString()) + parseNominal(admin_fee.toString()), "Nominal")}
                  >
                    📋
                  </button>
                  )}
                  
                </>
              ) : (
                <>
                  <span>Rp. {Number(paymentData!.price ).toLocaleString("id-ID") || 0}</span>
                  <button
                    className="text-blue-500 text-sm"
                    onClick={() => copyToClipboard(Number(paymentData!.price ).toString(), "Nominal")}
                  >
                    📋
                  </button>
                </>
              )
          }
          
        </div>

        <div className="flex justify-between items-center border-t pt-2 mt-2">
          <span className="text-sm text-gray-600 font-semibold">Jumlah Pembayaran</span>
          {idTransaction !== '' ? (
              <p className="text-sm font-bold text-gray-800">Rp. {Number(paymentHistory.data?.data.paid_amount || 0 + admin_fee ).toLocaleString("id-ID") || 0}</p>
            ) : (
              <span className="text-sm font-bold text-gray-800">Rp {Number(paymentData!.price ).toLocaleString("id-ID")}</span>
            )
          }
        </div>
      </div>
      </div>

      {/* Accordion Section */}
      <div className="p-4">
          <div className="bg-white p-2 rounded-lg shadow-md">
            <Accordion />
          </div>
      </div>
        

      {/* Button */}
      <div className="mt-6 p-4 space-y-2 mb-10">
        {idTransaction !== '' ? (
            <Button onClick={handlePrintPdf} className="w-full">Print Invoice</Button>
          ) : (
            <Button onClick={handleCekStatus} className="w-full">Cek status pembayaran</Button>
          )
        }
        <Button onClick={handleBackHome} className="w-full bg-red-500">Kembali ke home</Button>
      </div>
    </div>
  );
}
