export const bankInstructions: Record<
  string,
  { title: string; steps: string[] }[]
> = {
  BCA: [
    {
      title: "Melalui ATM BCA",
      steps: [
        "Masukkan kartu ATM BCA ke mesin ATM",
        "Pilih Bahasa yang diinginkan",
        "Masukkan PIN ATM Anda",
        "Pilih menu Transaksi Lainnya",
        "Pilih Transfer",
        "Pilih Ke Rekening BCA Virtual Account",
        "Masukkan Nomor Virtual Account (VA) yang sudah diberikan aplikasi",
        "Periksa kembali nama penerima dan jumlah tagihan yang muncul di layar",
        "Jika sudah benar, pilih Ya/Benar untuk konfirmasi",
        "Simpan struk bukti transaksi sebagai tanda pembayaran berhasil",
      ],
    },
    {
      title: "Melalui m-BCA (BCA Mobile)",
      steps: [
        "Buka aplikasi BCA Mobile di smartphone Anda",
        "Pilih menu m-BCA, lalu login dengan kode akses",
        "Pilih menu m-Transfer",
        "Pilih BCA Virtual Account",
        "Masukkan Nomor Virtual Account (VA)",
        "Periksa kembali detail pembayaran (nama penerima dan nominal)",
        "Jika sudah sesuai, klik OK",
        "Masukkan PIN m-BCA",
        "Tunggu hingga muncul notifikasi bahwa pembayaran berhasil",
      ],
    },
    {
      title: "Melalui myBCA",
      steps: [
        "Buka aplikasi myBCA di smartphone",
        "Login dengan BCA ID dan password atau biometric",
        "Pilih menu Transfer",
        "Pilih Ke Rekening Virtual Account BCA",
        "Masukkan Nomor Virtual Account (VA)",
        "Periksa kembali nama penerima dan jumlah tagihan",
        "Jika sudah sesuai, klik Lanjutkan",
        "Masukkan PIN myBCA",
        "Tunggu hingga muncul notifikasi bahwa pembayaran berhasil",
      ],
    },
    {
      title: "Melalui KlikBCA (Internet Banking BCA)",
      steps: [
        "Login ke situs KlikBCA Individual (https://ibank.klikbca.com)",
        "Masukkan User ID dan PIN Internet Banking",
        "Pilih menu Transfer Dana",
        "Klik Transfer ke BCA Virtual Account",
        "Masukkan Nomor Virtual Account (VA)",
        "Periksa kembali detail pembayaran yang tampil",
        "Masukkan PIN KeyBCA sesuai perintah yang muncul",
        "Klik Kirim/Submit",
        "Simpan bukti transaksi sebagai konfirmasi pembayaran berhasil",
      ],
    },
    {
      title: "Melalui Teller Bank BCA",
      steps: [
        "Datang ke cabang Bank BCA terdekat",
        "Ambil nomor antrian untuk Teller",
        "Sampaikan ke Teller bahwa ingin melakukan pembayaran ke Virtual Account BCA",
        "Isi formulir setor tunai / transfer dengan Nomor Virtual Account (VA) dan Nominal pembayaran",
        "Serahkan formulir beserta uang tunai (atau instruksi transfer dari rekening Anda) kepada Teller",
        "Teller akan memproses pembayaran",
        "Simpan bukti transaksi dari Teller sebagai konfirmasi pembayaran",
      ],
    },
    {
      title: "Melalui ATM Bank Lain (jaringan ATM Bersama/Prima/Alto)",
      steps: [
        "Masukkan kartu ATM dari bank lain",
        "Pilih Bahasa",
        "Masukkan PIN ATM",
        "Pilih menu Transfer Antar Bank",
        "Masukkan Kode Bank BCA (014)",
        "Masukkan Nomor Virtual Account (VA) setelah kode bank (contoh: 014123456789012)",
        "Masukkan jumlah pembayaran sesuai tagihan",
        "Periksa detail transaksi yang muncul",
        "Jika sudah benar, pilih Ya/OK untuk konfirmasi",
        "Simpan struk bukti transaksi",
      ],
    },
    {
      title: "Melalui Mobile Banking Bank Lain",
      steps: [
        "Buka aplikasi Mobile Banking dari bank Anda",
        "Login dengan User ID / PIN",
        "Pilih menu Transfer Antar Bank",
        "Pilih tujuan Bank BCA (kode 014)",
        "Masukkan Nomor Virtual Account (VA)",
        "Masukkan nominal pembayaran sesuai tagihan",
        "Periksa detail transaksi yang muncul",
        "Jika sudah benar, konfirmasi dan masukkan PIN/OTP",
        "Simpan bukti transaksi dari aplikasi",
      ],
    },
  ],
  NOBU: [
    {
      title: "Melalui ATM Bank Nobu",
      steps: [
        "Masukkan kartu ATM Bank Nobu",
        "Pilih Bahasa",
        "Masukkan PIN ATM",
        "Pilih menu Transfer atau Transaksi Lainnya, pilih Pembayaran, lalu Virtual Account",
        "Masukkan Nomor Virtual Account Nobu yang tertera pada aplikasi",
        "Periksa detail transaksi (nama penerima & nominal)",
        "Jika sudah sesuai, pilih Ya/OK untuk konfirmasi",
        "Simpan struk bukti pembayaran",
      ],
    },
    {
      title: "Melalui Nobu Internet Banking",
      steps: [
        "Login ke situs Nobu e-Banking",
        "Masukkan User ID dan Password",
        "Pilih menu Pembayaran, lalu Virtual Account",
        "Input Nomor Virtual Account Nobu",
        "Periksa detail transaksi",
        "Masukkan PIN/OTP token untuk konfirmasi",
        "Transaksi berhasil, simpan bukti pembayaran",
      ],
    },
    {
      title: "Melalui Nobu Mobile Banking",
      steps: [
        "Buka aplikasi Nobu Mobile Banking",
        "Login dengan User ID dan PIN/Password",
        "Pilih menu Transfer, lalu Virtual Account",
        "Masukkan Nomor Virtual Account Nobu",
        "Periksa detail (nama & nominal)",
        "Konfirmasi dengan PIN/OTP",
        "Simpan bukti transaksi",
      ],
    },
    {
      title: "Melalui Teller Bank Nobu",
      steps: [
        "Datang ke cabang Bank Nobu terdekat",
        "Ambil nomor antrian Teller",
        "Isi formulir setor tunai / transfer dengan Nomor Virtual Account Nobu dan Nominal pembayaran",
        "Serahkan formulir beserta uang tunai / instruksi transfer ke Teller",
        "Teller akan memproses pembayaran",
        "Simpan bukti transaksi dari Teller",
      ],
    },
    {
      title: "Melalui ATM Bank Lain (Jaringan ATM Bersama/Prima/Alto)",
      steps: [
        "Masukkan kartu ATM dari bank lain",
        "Pilih bahasa & masukkan PIN ATM",
        "Pilih menu Transfer Antar Bank",
        "Masukkan Kode Bank Nobu (503)",
        "Masukkan Nomor Virtual Account Nobu setelah kode bank (contoh: 503123456789012)",
        "Input nominal pembayaran sesuai tagihan",
        "Periksa detail transaksi",
        "Jika sudah sesuai, pilih Ya/OK",
        "Simpan struk bukti pembayaran",
      ],
    },
    {
      title: "Melalui Mobile Banking Bank Lain",
      steps: [
        "Buka aplikasi mobile banking bank Anda",
        "Login dengan User ID / PIN",
        "Pilih menu Transfer Antar Bank",
        "Pilih tujuan Bank Nobu (kode 503)",
        "Masukkan Nomor Virtual Account Nobu",
        "Input nominal pembayaran sesuai tagihan",
        "Konfirmasi detail, lalu masukkan PIN/OTP",
        "Simpan bukti transaksi",
      ],
    },
  ],
};
